openapi: 3.0.0
info:
  title: VERSIX NORMA - Edge Functions API
  version: 1.0.1
  description: |
    API Reference para Edge Functions (Supabase) do VERSIX NORMA.
    Todas as funções utilizam autenticação via JWT token do Supabase.
  contact:
    name: Versix Solutions
    url: https://versixnorma.com
servers:
  - url: https://{project-id}.functions.supabase.co
    variables:
      project-id:
        default: xxxxx
        description: Seu Project ID do Supabase

paths:
  /ask-norma:
    post:
      summary: Consultar Assistente de IA (Norma Chat)
      description: |
        Envia uma pergunta para o assistente de IA Norma.
        Integração com Groq API para respostas em tempo real.
        Fallback automático para respostas simuladas se GROQ_API_KEY não estiver configurado.
      operationId: askNorma
      tags:
        - AI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
                - condominioId
                - userId
              properties:
                message:
                  type: string
                  description: Pergunta do usuário
                  example: "Qual é o quórum mínimo para uma assembleia extraordinária?"
                condominioId:
                  type: string
                  format: uuid
                  description: ID do condomínio
                userId:
                  type: string
                  format: uuid
                  description: ID do usuário fazendo a pergunta
                conversationHistory:
                  type: array
                  description: Histórico de conversa anterior (opcional)
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                        enum: [user, assistant]
                      content:
                        type: string
                      timestamp:
                        type: string
                        format: date-time
      responses:
        '200':
          description: Resposta gerada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Resposta da Norma
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        document_type:
                          type: string
                        document_name:
                          type: string
                        page_number:
                          type: integer
        '400':
          description: Campos obrigatórios faltando
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Erro interno no processamento

  /send-emergency-alert:
    post:
      summary: Enviar Alerta de Emergência (SOS)
      description: |
        Dispara alertas de emergência via múltiplos canais.
        Integração com SMS (Twilio), Push Notifications, e contatos de emergência.
      operationId: sendEmergencyAlert
      tags:
        - Notifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - condominioId
                - userId
                - description
              properties:
                condominioId:
                  type: string
                  format: uuid
                userId:
                  type: string
                  format: uuid
                description:
                  type: string
                  example: "Incêndio na unidade 302"
                location:
                  type: object
                  properties:
                    latitude:
                      type: number
                    longitude:
                      type: number
                channels:
                  type: array
                  items:
                    type: string
                    enum: [sms, push, email, whatsapp]
      responses:
        '200':
          description: Alerta enviado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  alert_id:
                    type: string
                    format: uuid
                  notified:
                    type: integer
                    description: Número de pessoas notificadas
        '400':
          description: Validação falhou

  /send-email:
    post:
      summary: Enviar E-mail
      description: |
        Envia e-mail via SendGrid.
        Usado para notificações, convocações, avisos e comunicados.
      operationId: sendEmail
      tags:
        - Notifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - to
                - subject
                - html
              properties:
                to:
                  type: string
                  format: email
                subject:
                  type: string
                html:
                  type: string
                  description: Corpo do e-mail em HTML
                from:
                  type: string
                  format: email
                  default: noreply@versixnorma.com
      responses:
        '200':
          description: E-mail enviado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean

  /send-push:
    post:
      summary: Enviar Push Notification
      description: |
        Envia notificações push para dispositivos registrados.
        Usa Firebase Cloud Messaging (FCM).
      operationId: sendPush
      tags:
        - Notifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - body
              properties:
                title:
                  type: string
                body:
                  type: string
                icon:
                  type: string
                  description: URL do ícone (opcional)
                data:
                  type: object
                  description: Dados adicionais (chave-valor)
      responses:
        '200':
          description: Notificação enviada

  /send-sms:
    post:
      summary: Enviar SMS
      description: |
        Envia SMS via Twilio.
        Usado para alertas críticos e comunicados importantes.
      operationId: sendSms
      tags:
        - Notifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - to
                - message
              properties:
                to:
                  type: string
                  pattern: '^\+[0-9]{10,15}$'
                  example: "+5511999999999"
                message:
                  type: string
                  maxLength: 160
      responses:
        '200':
          description: SMS enviado com sucesso

  /health:
    get:
      summary: Health Check
      description: Verifica se a Edge Function está disponível
      operationId: healthCheck
      tags:
        - System
      responses:
        '200':
          description: Sistema saudável
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok]
                  timestamp:
                    type: string
                    format: date-time

  /collect-metrics:
    post:
      summary: Coletar Métricas de Uso
      description: |
        Registra métricas de uso e comportamento dos usuários.
        Armazena em PostgreSQL e envia dados para Sentry.
      operationId: collectMetrics
      tags:
        - Analytics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - condominioId
              properties:
                condominioId:
                  type: string
                  format: uuid
                event:
                  type: string
                  example: "norma_chat_message"
                data:
                  type: object
                  description: Dados específicos do evento
      responses:
        '200':
          description: Métrica registrada

  /verify-session:
    post:
      summary: Verificar Sessão do Usuário
      description: |
        Valida e renova o JWT token da sessão.
        Usada para garantir que usuário está autenticado.
      operationId: verifySession
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: JWT token (opcional, usa header Authorization se não fornecido)
      responses:
        '200':
          description: Sessão válida
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  userId:
                    type: string
                    format: uuid
                  expiresAt:
                    type: string
                    format: date-time
        '401':
          description: Sessão inválida ou expirada

  /approve-user:
    post:
      summary: Aprovar Novo Usuário
      description: |
        Aprova um usuário pendente para acesso ao sistema.
        Requer permissão de administrador.
      operationId: approveUser
      tags:
        - User Management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - usuario_id
                - acao
              properties:
                usuario_id:
                  type: string
                  format: uuid
                acao:
                  type: string
                  enum: [approve, reject]
                unidade_id:
                  type: string
                  format: uuid
                  description: (Opcional) Unidade a associar ao usuário
      responses:
        '200':
          description: Usuário aprovado/rejeitado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  usuario:
                    type: object
                    properties:
                      id:
                        type: string
                      nome:
                        type: string
                      status:
                        type: string
        '403':
          description: Sem permissão (não é admin)

  /validate-ata:
    post:
      summary: Validar Ata de Assembleia
      description: |
        Valida estrutura e conteúdo de uma ata antes de arquivo.
        Verifica quórum, assinaturas, e conformidade legal.
      operationId: validateAta
      tags:
        - Assembleias
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ataId
              properties:
                ataId:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Validação concluída
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  errors:
                    type: array
                    items:
                      type: string

  /uptime-check:
    get:
      summary: Verificar Disponibilidade do Sistema
      description: |
        Verifica status de todos os serviços críticos.
        Usado para monitoramento externo (Uptime Robot, etc).
      operationId: uptimeCheck
      tags:
        - System
      responses:
        '200':
          description: Todos os serviços estão funcionando
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok, degraded, down]
                  services:
                    type: object
                    properties:
                      supabase:
                        type: string
                      groq_api:
                        type: string
                      sendgrid:
                        type: string
                      timestamp:
                        type: string
                        format: date-time

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Token do Supabase (obtém via supabase.auth.session())

security:
  - BearerAuth: []

tags:
  - name: AI
    description: Funções de Inteligência Artificial
  - name: Notifications
    description: Notificações e Comunicações
  - name: Auth
    description: Autenticação e Sessões
  - name: Analytics
    description: Métricas e Análitica
  - name: User Management
    description: Gerenciamento de Usuários
  - name: Assembleias
    description: Funções de Assembleias
  - name: System
    description: Monitoramento e Status

x-documentation:
  - title: Autenticação
    description: |
      Todas as Edge Functions requerem autenticação via JWT.
      Obtenha o token assim:

      ```javascript
      const { data: { session } } = await supabase.auth.getSession();
      const token = session?.access_token;

      const response = await fetch('https://xxxxx.functions.supabase.co/ask-norma', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ message: '...', condominioId: '...', userId: '...' })
      });
      ```

  - title: Tratamento de Erros
    description: |
      Todos os endpoints retornam erros padrão:
      
      ```json
      {
        "error": "Descrição do erro",
        "code": "ERROR_CODE",
        "details": {}
      }
      ```

  - title: Rate Limiting
    description: |
      - ask-norma: 10 req/min por user
      - send-email: 100 req/min por condomínio
      - send-sms: 50 req/min por condomínio
      - Outros: 1000 req/min por projeto
